### ISSUE TITLE
Express example

### ISSUE THREAD

**Issue by cjpatoilo** [Aerolab/nextjs-pwa#3]
Any idea what the best way to run on express?

**Comment by RobertoGonzalez** [comment]
@cjpatoilo There's one example using Express in the official repo: https://github.com/zeit/next.js/tree/canary/examples/custom-server-express

**Comment by cjpatoilo** [comment]
@RobertoGonzalez I just forgot to describe my question better. It was about configuring the SW Precache plugin on Express. Sorry.
```
const path = require('path')
const express = require('express')
const next = require('next')

const port = parseInt(process.env.PORT, 10) || 3000
const server = express()
const app = next({ dev: process.env.NODE_ENV !== 'production' })

app
  .prepare()
  .then(() => {
    server
      .get('/sw.js', (req, res) => app.serveStatic(req, res, path.resolve('./static/sw.js')))
      .get('*',  app.getRequestHandler())
      .listen(port, err => console.log(err || `> Ready on http://localhost:${port}`))
  })
``` 

Anyway, thank for your attention.
👍

**Comment by RobertoGonzalez** [comment]
@cjpatoilo I haven't tested it, but that looks about right for express, assuming your serviceworker is named sw.js and you've written it by hand and placed it in static/sw.js. If you are using sw-precache, it's probably somewhere in the .next folder.

BTW, we switched to next-offline for serviceworkers, since it uses workbox and it caches all of the js necessary to run the app in a nicer way: https://github.com/hanford/next-offline

**Comment by nicer00ster** [comment]
@cjpatoilo Hey man. I was struggling with trying to implement a SW with my Express server as well, I finally figured it out today. Check out my repo if you're still having trouble! https://github.com/nicer00ster/nicer00ster-portfolio

EDIT: Thanks to your comment above I figured it out, so kudos to you my friend. =D
